from typing import TypedDict, List, Optional


# Structured output generated by Goal Parser node
class StructuredGoal(TypedDict):
    goal_type: str
    subject: List[str]
    location: Optional[str]
    constraints: List[str]
    expected_output: str


# Structure of each execution step generated by Planner node
class PlanStep(TypedDict):
    step: int
    action: str
    description: str


# Structure of each execution step result generated by Executor node
class StepResult(TypedDict):
    step: int
    action: str
    result: str


# Shared memory object for the entire LangGraph workflow
class AgentState(TypedDict):

    # Original user goal/input
    raw_goal: str

    # Structured goal generated by Goal Parser node
    structured_goal: Optional[StructuredGoal]

    # Step-by-step execution plan generated by Planner node
    execution_plan: Optional[List[PlanStep]]

    # Results of each executed step
    execution_results: Optional[List[StepResult]]

    # Verifier feedback and routing
    verification_feedback: Optional[str]
    steps_to_retry: Optional[List[int]]
    retry_count: int

    # Insights synthesized from execution results
    synthesized_insights: Optional[List['ReportSection']]

    # Final formatted markdown report
    final_report: Optional[str]

class ReportSection(TypedDict):
    title: str
    content: str
